[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
primaryColor = "#002857"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E11A27"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = true

[client]
showSidebarNavigation = true